---
echo: false
title: COMP2870 Theoretical Foundations of Computer Science II
subtitle: Analysis of errors
author:
  - name: Dr. Thomas Ranner (Tom)
    email: T.Ranner@leeds.ac.uk
    affiliation: School of Computer Science, University of Leeds
code-line-numbers: true
html-math-method: mathjax
include-in-header:
  - ../mathjax.html
  - ../grid-background.html

format:
  live-revealjs:
    slide-level: 3
    slide-number: true
    preview-links: auto
    chalkboard:
      theme: whiteboard
---

# Exact derivatives and exact solutions

```{python}
import time
from collections import defaultdict

import numpy as np
import pandas as pd
from IPython.display import Markdown
from matplotlib import pyplot as plt

plt.style.use("seaborn-v0_8-colorblind")


def sci_tex(x, sig=4):
    if x == 0 or (isinstance(x, float) and np.isclose(x, 0)):
        return "0"
    if np.isnan(x):
        return "---"
    exp = int(np.floor(np.log10(abs(x))))
    mant = x / (10**exp)
    return rf"\({mant:.{sig - 1}f}\times 10^{{{exp}}}\)"


def table_styler(df):
    return df.style.format(
        {
            "h": sci_tex,
            "Abs. error": sci_tex,
            "Run time": sci_tex,
        },
        na_rep="---",
    ).hide()


```


> Use exact solutions to calculate errors in numerical methods for differential equations,\
> Calculate rates of convergence for differential equation solvers.

::: {.notes}
In a small number of cases, it is possible to solve differential equations *exactly*. That is to write down a simple expression for the function which satisfies both the differential equation and its initial condition. This is rare and is the main reason why we use numerical methods. However, the special cases where we can find exact solutions are useful for testing our numerical methods.
:::

## Example

Consider $y(t) = t^3$, we can compute that
$$
y'(t) = 3 t^2 = \frac{3 y(t)}{t}.
$$
Hence, we know the solution to the following equation:
\begin{equation}
\label{eq:diff-eq}
y'(t) = \frac{3 y(t)}{t} \quad \text{subject to} \quad y(1) = 1.
\end{equation}
If we solve this differential equation for $t$ between $1$ and $2$, say, then we know that the exact answer when $t=2$ is $y(2) = 8$.


::: {.notes}
Note here that we start from $t=1$ to avoid dividing by zero at $t=0$.
We will use this differential equation where we know the exact solution to test Euler's method.
:::

---

Recall that for a differential equation given by:
\begin{multline*}
y'(t) = f(t, y(t)) \\\text{subject to the initial condition}\quad y(t_0) = y_0.
\end{multline*}

Euler's method is given by:

1. Set initial values $t^{(0)}$ and $y^{(0)}$ from the initial condition.
2. Loop over all time steps, until the final time $T$, updating using the formula:
   \begin{align*}
   y^{(i+1)} &= y^{(i)} + h f(t^{(i)}, y^{(i)}) \\
   t^{(i+1)} &= t^{(i)} + h.
   \end{align*}

##  {.gridbg}

::: {#exr-euler-error}
Compute two time steps of Euler's method to approximate the solution of
\begin{equation}
y'(t) = \frac{3 y(t)}{t} \quad \text{subject to} \quad y(1) = 1.
\end{equation}
at time $T=2$. What is the error between your computed solution and the exact solution ($y(2) = 8$)?

::: {.columns}
::: {.column}
Submit your solution using vevox.app ID 130-942-368.

::: {style="color:#6f6f6f; font-size:0.9em;"}
Euler step: $y^{(i+1)} = y^{(i)} + h f(t^{(i)}, y^{(i)})$, $t^{(i+1)} = t^{(i)} + h$.
:::
:::

::: {.column}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" shape-rendering="crispEdges"><path fill="#ffffff" d="M0 0h27v27H0z"></path><path stroke="#000000" d="M1 1.5h7m1 0h1m1 0h3m1 0h1m1 0h1m1 0h7M1 2.5h1m5 0h1m1 0h2m8 0h1m5 0h1M1 3.5h1m1 0h3m1 0h1m1 0h1m1 0h2m1 0h4m1 0h1m1 0h3m1 0h1M1 4.5h1m1 0h3m1 0h1m2 0h2m3 0h1m3 0h1m1 0h3m1 0h1M1 5.5h1m1 0h3m1 0h1m1 0h1m2 0h2m3 0h1m1 0h1m1 0h3m1 0h1M1 6.5h1m5 0h1m2 0h2m5 0h1m1 0h1m5 0h1M1 7.5h7m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m1 0h7M10 8.5h2m1 0h3M1 9.5h1m2 0h6m1 0h3m2 0h1m1 0h1m2 0h1m1 0h3M1 10.5h1m4 0h1m3 0h4m1 0h2m3 0h5M1 11.5h3m2 0h2m3 0h3m2 0h2m1 0h1m2 0h1m2 0h1M1 12.5h2m1 0h2m2 0h1m1 0h3m1 0h1m2 0h1m1 0h2m1 0h4M1 13.5h3m2 0h2m2 0h1m3 0h4m1 0h1m5 0h1M1 14.5h2m7 0h2m1 0h6m2 0h1m2 0h1M1 15.5h5m1 0h4m5 0h4m1 0h5M1 16.5h1m1 0h2m1 0h1m2 0h1m1 0h1m1 0h4m3 0h1m1 0h2m1 0h1M1 17.5h1m1 0h1m1 0h1m1 0h2m1 0h5m2 0h5m1 0h2M9 18.5h2m1 0h1m1 0h1m2 0h1m3 0h1m1 0h2M1 19.5h7m1 0h3m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m3 0h1M1 20.5h1m5 0h1m1 0h1m2 0h1m4 0h1m3 0h1M1 21.5h1m1 0h3m1 0h1m1 0h1m2 0h3m1 0h6m3 0h1M1 22.5h1m1 0h3m1 0h1m1 0h1m1 0h1m1 0h1m3 0h3m4 0h2M1 23.5h1m1 0h3m1 0h1m3 0h4m1 0h3m2 0h5M1 24.5h1m5 0h1m4 0h2m1 0h2m3 0h2m1 0h3M1 25.5h7m1 0h1m2 0h4m1 0h1m4 0h1m2 0h1"></path></svg>
:::
:::
:::

---

We can also implement Euler's method in code:

```{python}
# | echo: False
data = {}

for n in [10, 20, 40, 80, 160]:
    # set up storage for all time steps
    h = (2 - 1) / n
    t, y = np.empty((n + 1,)), np.empty((n + 1,))

    # perform time stepping
    t[0], y[0] = 1.0, 1.0
    for i in range(n):
        t[i + 1], y[i + 1] = t[i] + h, y[i] + h * (3 * y[i]) / t[i]

    # store data
    data[n] = (t, y)
```

```{python}
fig, axs = plt.subplots(1, 2)

for n, (t, y) in data.items():
    axs[0].plot(t, y, ".-", label=f"{n=}")
    axs[1].plot(t, y, ".-")

for ax in axs:
    ax.set_xlabel("t")
    ax.set_ylabel("y(t)")
    ax.grid(True)

axs[1].set_xlim([1.95, 2.0])
axs[1].set_ylim([7.5, 8.0])
axs[0].legend()

plt.tight_layout()
plt.show()

```

::: {.notes}
We can see that as we increase the number of steps $n$ (reduce the time step $h$), our solutions become better and better.
:::

---

We can also co using the *absolute error*
$$
\text{absolute error} = |y^{(n)} - y(2)|,
$$
where $y^{(n)}$ is the solution at the final time step.

```{python}
# | label: tbl-euler-errors
error_table = defaultdict(list)

for n, (_, y) in data.items():
    h = (2 - 1) / n
    solution = y[-1]
    abs_error = abs(y[-1] - 8.0)

    error_table["n"].append(n)
    error_table["h"].append(h)
    error_table["Solution"].append(solution)
    error_table["Abs. error"].append(abs_error)

df = pd.DataFrame(error_table)
df["ratio"] = df["Abs. error"] / df["Abs. error"].shift()

table_styler(df)
```

::: {.notes}
This table shows that indeed the absolute error is decreasing as $h \to 0$. We also compute the ratio between different errors. We see that each time $h$ is halved, that the error is approximately halved. In other words, the error is approximately proportional to $h$.

::: {#exr-euler-ratio}
What might we expect the computed solution to be if we halved $h$ one more time?
:::
:::

---

::: {.notes}
Something interesting happens when we plot $h$ against the absolute error for Euler's method - we see that the errors all fall on a straight line. Perhaps this is not too strange since we think that the error is approximately proportional to step size, so this line should be straight either on a linear or log scale.
:::

```{python}
fig, axs = plt.subplots(1, 2)
axs[0].semilogx(
    error_table["h"], [8.0 for _ in error_table["h"]], label="exact"
)

axs[0].semilogx(
    error_table["h"], error_table["Solution"], "C1o-", label="Euler"
)
axs[1].loglog(error_table["h"], error_table["Abs. error"], "C1o-")

axs[0].set_xlabel("$h$")
axs[0].set_ylabel("Solution")
axs[1].set_xlabel("$h$")
axs[1].set_ylabel("Abs. error")

axs[0].grid(True)
axs[1].grid(True)

axs[0].legend()

plt.tight_layout()
plt.show()

```

---

:::: {#rem-log-scale}
Using log scales is really important when considering variables like $h$ or error. Contrast the above nice plot, with nice evenly spread data points, with these linear scaled plots:


```{python}
fig, axs = plt.subplots(1, 2)
axs[0].semilogx(
    error_table["h"], [8.0 for _ in error_table["h"]], label="exact"
)
axs[0].plot(error_table["h"], error_table["Solution"], "C1o-", label="Euler")
axs[1].plot(error_table["h"], error_table["Abs. error"], "C1o-")

axs[0].set_xlabel("$h$")
axs[0].set_ylabel("Solution")
axs[1].set_xlabel("$h$")
axs[1].set_ylabel("Abs. error")

axs[0].grid(True)
axs[1].grid(True)

axs[0].legend()

plt.tight_layout()
plt.show()

```

::: {#exr-log-scale}
Why don't we use a log scale for solution too?
:::
::::

::: {.notes}
It is important to note that in this lecture, we are measuring the error at the final time point as a measure of how good our method is. This is a *global error* that measures the accumulation of *local errors* which happen at each time step. Other possible global errors include finding the maximum or average error over all time steps.

Sometimes we also care more about other, more physical based properties of our solution. For example, in long-time simulations scientists often want to ensure that the laws of thermodynamics are implemented exactly -- i.e. that energy is conserved and that entropy increases.
:::

## Big $O$ notation

When considering algorithm complexity, you have already seen big $O$ notation. For example:

- Gaussian elimination requires $O(n^3)$ operations when $n$ is large,
- Backward substitution requires $O(n^2)$ operations when $n$ is large.

---

For large values of $n$ the *highest* powers of $n$ are the *most* significant. For smaller values of $h$, it is the *lowest* powers of $h$ that are the most significant. When $h = 0.001$, $h$ is much bigger than $h^2$, for example.

We can make use of the big $O$ notation in either case.
Formally, we say that $f(h) = O(h^p)$ as $h \to 0$ if there exists a constant $C > 0$ such that $|f(h)| < C |h|^p$ for all small enough $h$.

---

::: {#exm-bigO}
Let $f(x) = 2x^2 + 4x^3 + x^5 + 2x^6$,

- then $f(x) = O(x^6)$ as $x \to \infty$,
- and $f(x) = O(x^2)$ as $x \to 0$.
:::

In this notation, we can say that **the error in Euler's method is $O(h)$.**

# The midpoint method -- an improvement on Euler's method

> Solve differential equations numerically using the midpoint method

## {.gridbg}

::: {.notes}
Let's assume that the error in Euler's method is exactly proportional to $h$. In this case, if we halve $h$, we halve the error. In this derivation, we will start from the initial condition and want to approximate the solution after a time $h$. We will label the exact solution at $t=h$ by $y_{\text{exact}}$.

- Then, we continue by computing one time step from $y^{(0)}$ with time step $h$ - we call this solution $z_1$. We label error between the exact solution and $z_1$ by $E_1$.
- We then take two time steps from $y^{(0)}$ now with time step $h/2$ - we call this solution $z_2$. We label the error between the exact solution and $z_2$ by $E_2$. Since in this derivation, the error is exactly proportional to the time step, we can see that $E_2 = \frac{E_1}{2}$.

In equations, we can express these relations as:
\begin{align*}
z_1 - y_{\text{exact}} & = E_1 \\
z_2 - y_{\text{exact}} & = E_2 = \frac{E_1}{2}.
\end{align*}
Subtracting twice the second equation from the first equation gives:
$$
y_{\text{exact}} = 2 z_2 - z_1.
$$
If our assumption that the error in Euler's method is exactly proportional to $h$, combining $z_1$ and $z_2$ would give a solution with zero error! However, our assumption is in fact approximately true as we found in @tbl-euler-errors. So we might hope that we have found a method with smaller error than Euler's method with three times the cost of Euler's method (i.e. 3 Euler steps per one time step of this method - one to find $z_1$ and two to find $z_2$).

We can even formulate this method more compactly. Writing our new scheme in full, for a general time step $i$, we have
for the one step approach:
\begin{align*}
z_1 & = y^{(i)} + h f(t^{(i)}, y^{(i)}),
\end{align*}
and for the two step approach:
\begin{align*}
k & = y^{(i)} + \frac{h}{2} f(t^{(i)}, y^{(i)}) \\
m & = t^{(i)} + \frac{h}{2} \\
z_2 & = k + \frac{h}{2} f(m, k).
\end{align*}
Combining $z_1$ and $z_2$ as suggested above we see:
\begin{align*}
y^{(i+1)}
& = 2 z_2 - z_1 \\
& = 2 \left(k + \frac{h}{2} f(m, k)\right) - \left(y^{(i)} + h f(t^{(i)}, y^{(i)})\right)
&& \text{(substitute for $z_1$ and $z_2$)} \\
& = 2 k - y^{(i)} + h \left( f(m, k) - f(t^{(i)}, y^{(i)}) \right)
&& \text{(rearrange)} \\
& = 2 \left(y^{(i)} + \frac{h}{2} f(t^{(i)}, y^{(i)}) \right) - y^{(i)} + h \left( f(m, k) - f(t^{(i)}, y^{(i)}) \right)
&& \text{(substitute for $k$)} \\
& = 2 y^{(i)} - y^{(i)} + h \left( f(t^{(i)}, y^{(i)}) + f(m, k) - f(t^{(i)}, y^{(i)}) \right) \\
& = y^{(i)} + h f(m, k).
\end{align*}
:::

## The algorithm

1. Initialise starting values $t^{(0)}$ and $y^{(0)}$.
2. Loop over all time steps, until the final time, updating using the formulae:
   \begin{align*}
    k & = y^{(i)} + \frac{h}{2} f(t^{(i)}, y^{(i)}) \\
    m & = t^{(i)} + \frac{h}{2} \\
    y^{(i+1)} & = y^{(i)} + h f(m, k) \\
    t^{(i+1)} & = t^{(i)} + h.
   \end{align*}

::: {.notes}
In the end the cost of this formulation of the midpoint method is twice as large as Euler's method.
:::

## Example {.smaller .gridbg}

::: {.columns}
::: {.column}
Take two steps of the midpoint rule to approximate the solution of
\begin{multline*}
y'(t) = -y(t)^2 \\\text{subject to the initial condition} \quad y(0) = 2,
\end{multline*}
for $0 \le t \le 2$.

::: {style="color:#6f6f6f; font-size:0.9em;"}
$k = y^{(i)} + \frac{h}{2} f(t^{(i)}, y^{(i)})$,
$m = t^{(i)} + \frac{h}{2}$,
$y^{(i+1)} = y^{(i)} + h f(m, k)$,
$t^{(i+1)} = t^{(i)} + h$.
:::
:::

::: {.column}
:::
:::

::: {.notes}
```{python}
t0 = 0
y0 = 2
T = 2

n = 2
h = (T - t0) / n


def f(_, y):
    return -(y**2)


s = f"""
In this example we have:

- $n={n}$
- $t_0 = {t0}$
- $y_0 = {y0}$
- $T = {T}$
- $h = ({T} - {t0})/{n} = {h}$
- $f(t, y) = -y^2$.

We start with $t^{{(0)}} = {t0}$ and $y^{{(0)}} = {y0}$.

"""

t, y = t0, y0

for step in range(n):
    k = y + (h / 2) * f(t, y)
    m = t + h / 2
    ynew = y + h * f(m, k)
    tnew = t + h

    s_step = f"""
- Step {step + 1}:
    \\begin{{align*}}
      k & = y^{{({step})}} + \\frac{{h}}{{2}} f(t^{{({step})}}, y^{{({step})}})
      \\\\
      & = {y} + \\frac{{{h}}}{{2}} \\times (-({y})^2) \\\\
      & = {y} + {h / 2} \\times {f(t, y)} = {k} \\\\
      m & = t^{{({step})}} + \\frac{{h}}{{2}} \\\\
      & = {t} + \\frac{{{h}}}{{2}} = {m} \\\\
      y^{{({step + 1})}} & = y^{{({step})}} + h
       f(m, k) \\\\
      & = {y} + {h} (-({k})^2) \\\\
      & = {y} + {h} \\times {f(m, k)} = {ynew} \\\\
      t^{{({step + 1})}} & = t^{{({step})}} + h \\\\
      & = {t} + {h} = {tnew}.
    \\end{{align*}}
    """
    s += s_step

    t, y = tnew, ynew


Markdown(s)
```
:::

##  {.smaller .gridbg}

::: {#exr-midpoint-error}
Compute one time step of the midpoint method to approximate the solution of
\begin{equation}
y'(t) = \frac{3 y(t)}{t} \quad \text{subject to} \quad y(1) = 1.
\end{equation}
at time $T=2$. What is the error between your computed solution and the exact solution ($y(2) = 8$)?

::: {.columns}
::: {.column}
Submit your solution using vevox.app ID 130-942-368.

::: {style="color:#6f6f6f; font-size:0.9em;"}
$k = y^{(i)} + \frac{h}{2} f(t^{(i)}, y^{(i)})$,
$m = t^{(i)} + \frac{h}{2}$,
$y^{(i+1)} = y^{(i)} + h f(m, k)$,
$t^{(i+1)} = t^{(i)} + h$.
:::
:::

::: {.column}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" shape-rendering="crispEdges"><path fill="#ffffff" d="M0 0h27v27H0z"></path><path stroke="#000000" d="M1 1.5h7m1 0h1m1 0h3m1 0h1m1 0h1m1 0h7M1 2.5h1m5 0h1m1 0h2m8 0h1m5 0h1M1 3.5h1m1 0h3m1 0h1m1 0h1m1 0h2m1 0h4m1 0h1m1 0h3m1 0h1M1 4.5h1m1 0h3m1 0h1m2 0h2m3 0h1m3 0h1m1 0h3m1 0h1M1 5.5h1m1 0h3m1 0h1m1 0h1m2 0h2m3 0h1m1 0h1m1 0h3m1 0h1M1 6.5h1m5 0h1m2 0h2m5 0h1m1 0h1m5 0h1M1 7.5h7m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m1 0h7M10 8.5h2m1 0h3M1 9.5h1m2 0h6m1 0h3m2 0h1m1 0h1m2 0h1m1 0h3M1 10.5h1m4 0h1m3 0h4m1 0h2m3 0h5M1 11.5h3m2 0h2m3 0h3m2 0h2m1 0h1m2 0h1m2 0h1M1 12.5h2m1 0h2m2 0h1m1 0h3m1 0h1m2 0h1m1 0h2m1 0h4M1 13.5h3m2 0h2m2 0h1m3 0h4m1 0h1m5 0h1M1 14.5h2m7 0h2m1 0h6m2 0h1m2 0h1M1 15.5h5m1 0h4m5 0h4m1 0h5M1 16.5h1m1 0h2m1 0h1m2 0h1m1 0h1m1 0h4m3 0h1m1 0h2m1 0h1M1 17.5h1m1 0h1m1 0h1m1 0h2m1 0h5m2 0h5m1 0h2M9 18.5h2m1 0h1m1 0h1m2 0h1m3 0h1m1 0h2M1 19.5h7m1 0h3m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m3 0h1M1 20.5h1m5 0h1m1 0h1m2 0h1m4 0h1m3 0h1M1 21.5h1m1 0h3m1 0h1m1 0h1m2 0h3m1 0h6m3 0h1M1 22.5h1m1 0h3m1 0h1m1 0h1m1 0h1m1 0h1m3 0h3m4 0h2M1 23.5h1m1 0h3m1 0h1m3 0h4m1 0h3m2 0h5M1 24.5h1m5 0h1m4 0h2m1 0h2m3 0h2m1 0h3M1 25.5h7m1 0h1m2 0h4m1 0h1m4 0h1m2 0h1"></path></svg>
:::
:::

:::

## Numerical results

We can also implement the method in code and explore how the error changes as we change the number of steps.

::: {.notes}
 For this test we use the same test as we did for Euler's method \eqref{eq:diff-eq}.
:::

```{python}
data_mp = {}

for n in [10, 20, 40, 80, 160]:
    h = (2 - 1) / n
    t, y = np.empty((n + 1,)), np.empty((n + 1,))

    t[0], y[0] = 1.0, 1.0
    for i in range(n):
        m, k = t[i] + h / 2, y[i] + (h / 2) * (3 * y[i]) / t[i]
        t[i + 1], y[i + 1] = t[i] + h, y[i] + h * (3 * k) / m

    data_mp[n] = (t, y)
```

```{python}
fig, axs = plt.subplots(1, 2)

for n, (t, y) in data_mp.items():
    axs[0].plot(t, y, ".-", label=f"{n=}")
    axs[1].plot(t, y, ".-")

for ax in axs:
    ax.set_xlabel("t")
    ax.set_ylabel("y(t)")
    ax.grid(True)

axs[1].set_xlim([1.95, 2.0])
axs[1].set_ylim([7.5, 8.0])
axs[0].legend()

plt.tight_layout()
plt.show()

```

::: {.notes}
We already see that we are much closer to the solution.
:::
---

```{python}
# | label: tbl-midpoint-errors
# | tbl-cap: A convergence study for the midpoint method
error_table_mp = defaultdict(list)

for n, (_, y) in data_mp.items():
    h = (2 - 1) / n
    solution = y[-1]
    abs_error = abs(y[-1] - 8.0)

    error_table_mp["n"].append(n)
    error_table_mp["h"].append(h)
    error_table_mp["Solution"].append(solution)
    error_table_mp["Abs. error"].append(abs_error)

df_mp = pd.DataFrame(error_table_mp)
df_mp["ratio"] = df_mp["Abs. error"] / df_mp["Abs. error"].shift()

table_styler(df_mp)
```

::: {.notes}
We now see that the error reduces by a *quarter* each time we reduce $h$ by half. This means that the error is approximately proportional to $h^2$, or equivalently, we can say that the error is $O(h^2)$ as $h \to 0$.
:::

This is a significant improvement on Euler's method. We say that the midpoint method is **second order**, whereas Euler's method is just **first order**.

---

We can see the significant reduction in error by plotting the errors for both methods:

```{python}
fig, axs = plt.subplots(1, 2)

axs[0].plot(error_table["h"], [8.0 for _ in error_table["h"]], label="exact")

axs[0].semilogx(
    error_table["h"], error_table["Solution"], "C1o-", label="Euler"
)
axs[1].loglog(error_table["h"], error_table["Abs. error"], "C1o-")

axs[0].semilogx(
    error_table_mp["h"], error_table_mp["Solution"], "C2o-", label="midpoint"
)
axs[1].loglog(error_table_mp["h"], error_table_mp["Abs. error"], "C2o-")

axs[0].set_xlabel("$h$")
axs[0].set_ylabel("Solution")
axs[1].set_xlabel("$h$")
axs[1].set_ylabel("Abs. error")

axs[0].grid(True)
axs[1].grid(True)

axs[0].legend()

plt.tight_layout()
plt.show()

```

::: {.notes}
Our interesting phenomenon of the straight line on the log-log plot of $h$ and absolute error has happened again for the midpoint method. The difference now is that the line is much steeper. In a log-log plot, straight lines correspond to power laws (i.e., $C h^p$) and the slope indicates the exponent in the power law ($p$). Indeed if $\text{error}(h) \approx C h^p$ then
$$
\log(\text{error}(h)) \approx \log C + p \log h.
$$

We are seeing that our method behaves as if the error is proportional to $h^2$.
:::

# Balancing cost and accuracy

> Explain how to balance accuracy and efficiency when solving differential equations numerically.

---

- The methods seem to show a trade-off between small errors and cheaper methods
- Let's run the same tests but now we measure the run time and number of right-hand side evaulations


::: {.notes}
At first glance, it may seem that we now have a trade-off between reducing the error but at a higher cost by using the midpoint method. We can test this more explicitly. We repeat the experiments but use two additional measures of cost: the run time and the number of right-hand side ($f$) evaluations. When working with real-world systems, evaluating the right-hand side function often forms the main computational cost of both Euler's method and the midpoint method.
:::

---

```{python}
data_euler = {}
data_midpoint = {}
repeats = 10

# -- euler's method --
for n in [10, 20, 40, 80, 160]:
    # set up storage for all time steps
    h = (2 - 1) / n
    t, y = np.empty((n + 1,)), np.empty((n + 1,))

    # start timer
    start_time = time.perf_counter()
    for _ in range(repeats):
        # counter for rhs evaluations
        f_evals = 0

        t[0], y[0] = 1.0, 1.0
        for i in range(n):
            t[i + 1], y[i + 1] = t[i] + h, y[i] + h * (3 * y[i]) / t[i]
            f_evals += 1

    # stop timer
    end_time = time.perf_counter()
    run_time = (end_time - start_time) / repeats
    # store data
    data_euler[n] = (t, y, run_time, f_evals)

# -- midpoint method --
for n in [10, 20, 40, 80, 160]:
    # set up storage for all time steps
    h = (2 - 1) / n
    t, y = np.empty((n + 1,)), np.empty((n + 1,))

    # start timer
    start_time = time.perf_counter()
    for _ in range(repeats):
        # reset counter for rhs evaluations
        f_evals = 0

        t[0], y[0] = 1.0, 1.0
        for i in range(n):
            m, k = t[i] + h / 2, y[i] + (h / 2) * (3 * y[i]) / t[i]
            t[i + 1], y[i + 1] = t[i] + h, y[i] + h * (3 * k) / m
            f_evals += 2

    # stop timer
    end_time = time.perf_counter()
    run_time = (end_time - start_time) / repeats
    # store data
    data_midpoint[n] = (t, y, run_time, f_evals)

```

```{python}
error_cost_table_euler = defaultdict(list)

for n, (_, y, run_time, f_evals) in data_euler.items():
    h = (2 - 1) / n
    solution = y[-1]
    error = abs(solution - 8.0)

    error_cost_table_euler["n"].append(n)
    error_cost_table_euler["h"].append(h)
    error_cost_table_euler["Solution"].append(solution)
    error_cost_table_euler["Abs. error"].append(error)
    error_cost_table_euler["Run time"].append(run_time)
    error_cost_table_euler["Rhs evals"].append(f_evals)

df_euler = pd.DataFrame(error_cost_table_euler)
df_euler["Run time ratio"] = df_euler["Run time"] / df_euler["Run time"].shift()

error_cost_table_midpoint = defaultdict(list)

for n, (_, y, run_time, f_evals) in data_midpoint.items():
    h = (2 - 1) / n
    solution = y[-1]
    error = abs(solution - 8.0)

    error_cost_table_midpoint["n"].append(n)
    error_cost_table_midpoint["h"].append(h)
    error_cost_table_midpoint["Solution"].append(solution)
    error_cost_table_midpoint["Abs. error"].append(error)
    error_cost_table_midpoint["Run time"].append(run_time)
    error_cost_table_midpoint["Rhs evals"].append(f_evals)

df_midpoint = pd.DataFrame(error_cost_table_midpoint)
df_midpoint["Run time ratio"] = (
    df_midpoint["Run time"] / df_midpoint["Run time"].shift()
)
```

```{python}
# | label: tbl-euler-error-cost
# | tbl-cap: A convergence study for Euler's method with running costs
table_styler(df_euler[["n", "h", "Run time", "Rhs evals", "Run time ratio"]])

```

---

```{python}
# | label: tbl-midpoint-error-cost
# | tbl-cap: A convergence study for Midpoint's method with running costs
table_styler(df_midpoint[["n", "h", "Run time", "Rhs evals", "Run time ratio"]])

```

---

```{python}
fig, axs = plt.subplots(1, 2)

axs[0].loglog(df_euler["h"], df_euler["Run time"], "o-", label="Euler")
axs[1].loglog(df_euler["h"], df_euler["Rhs evals"], "o-", label="Euler")
axs[0].loglog(df_midpoint["h"], df_midpoint["Run time"], "o-", label="Midpoint")
axs[1].loglog(
    df_midpoint["h"], df_midpoint["Rhs evals"], "o-", label="Midpoint"
)

for ax in axs:
    ax.set_xlabel("$h$")
    ax.grid(True)

axs[0].set_ylabel("Run time")
axs[1].set_ylabel("Rhs evaluations")

axs[0].legend()
plt.tight_layout()
plt.show()


```

---

However, we can make this plot another way by plotting the cost against the error.

```{python}
fig, axs = plt.subplots(1, 2)

axs[0].loglog(df_euler["Run time"], df_euler["Abs. error"], "o-", label="Euler")
axs[1].loglog(
    df_euler["Rhs evals"], df_euler["Abs. error"], "o-", label="Euler"
)
axs[0].loglog(
    df_midpoint["Run time"], df_midpoint["Abs. error"], "o-", label="Midpoint"
)
axs[1].loglog(
    df_midpoint["Rhs evals"], df_midpoint["Abs. error"], "o-", label="Midpoint"
)

for ax in axs:
    ax.set_ylabel("Abs. error")
    ax.grid(True)

axs[0].set_xlabel("Run time")
axs[1].set_xlabel("Rhs evaluations")

axs[0].legend()
plt.tight_layout()
plt.show()


```

---

- We see now that whichever way you want to measure cost, you see that for a fixed cost the midpoint method gives a lower error.
- Although the midpoint method costs about twice as much per time step, its higher order accuracy means we need far fewer steps to reach a desired accuracy.
- So the best way to think is that if you have a budget of, say, right-hand side evaluations, $N$, you can afford for your computations, then in general, you should choose to use the midpoint method with $n=N/2$ time steps in order to minimise the error.
